### ISSUE TITLE
Several str to bytes errors with python 3.7.x

### ISSUE THREAD

**Issue by croessner** [decalage2/oletools#622] opened 2020-09-24 17:02 UTC
**Affected tool:**
olevba

**Describe the bug**
By running olevba with a test infected DOC document, the olevba script in version 0.55 throws tracebacks about str and bytes concat errors. I guess it are some minor python coding bugs. I fixed them and provide a diff file. Please review and if okay, apply it to olevba.

[str_to_bytes_fix.diff.zip](https://github.com/decalage2/oletools/files/5277865/str_to_bytes_fix.diff.zip)

**Comment by decalage2** [comment] 2020-09-24 19:39
Thanks for reporting it, I think this has already been fixed in the dev version. See issue #455 for details.
Please test with the dev version: https://github.com/decalage2/oletools/wiki/Install#how-to-install-the-latest-development-version
For now I'm closing this issue, as it looks like a duplicate of #455.

**Closed by decalage2** 2020-09-24 19:39 UTC
Labels: :bug: bug, duplicate, olevba
